### ISSUE TITLE
Issue with first join command

### ISSUE THREAD

**Issue by ArcadeFighter** [diogotcorreia/Triton#87] opened 2020-03-08 23:18 UTC
**Describe the bug**
When i join at lobby server for the first time, triton pate some error with plugin FirstJoinPlus (Spigot link: https://www.spigotmc.org/resources/firstjoinplus.29804/)

**To Reproduce**
Join for the first time with FirstJoinPlus plugin.

**Expected behavior**
When i join for the first time, it paste error into console and show error language.

**Screenshots (optional)**
https://cdn.discordapp.com/attachments/395566597860884480/686144385372651580/unknown.png

**Server information (please complete the following information):**
 - Server Minecraft Version: 1.12.2
 - Client Minecraft Version: 1.12.2
 - Aegis Bungeecord fork
 - Triton Version: 2.5.1

**Additional context**
https://pastebin.com/UdpKHS7m

**Comment by diogotcorreia** [comment] 2020-03-09 09:53
![image](https://user-images.githubusercontent.com/7467891/76201794-bd569b80-61eb-11ea-9003-1286e0cd9ced.png)
It seems to be working for me.
Could you send me your FirstJoinPlus config?

**Comment by diogotcorreia** [comment] 2020-03-09 23:34
Can't reproduce the issue. Closing this.

**Closed by diogotcorreia** 2020-03-09 23:34 UTC
Labels: bug, can't reproduce
