### ISSUE TITLE
PlaceholderAPI and TAB plugin compatibility

### ISSUE THREAD

**Issue by TadiklCZE** [diogotcorreia/Triton#95] opened 2020-03-15 16:24 UTC
**Describe the bug**
Hello after using the TAB plugin as a Scoreboard manager, it sometimes bugs. It disable a scoreboard. When I looked into an error log, it was full of Triton Placeholders errors.

**Errors**
https://pastebin.com/0X5GEnyt

**Server information (please complete the following information):**
 - Server Minecraft Version: 1.12.2
 - Client Minecraft Version (if using ViaVersion or something similar): 1.12.2
 - BungeeCord (specify if it's a fork) [yes or no] Yes (Aegis fork)
 - Triton Version: 2.6.2

**Comment by TadiklCZE** [comment] 2020-03-15 17:24
Here is a new error [https://pastebin.com/0X5GEnyt]

**Comment by diogotcorreia** [comment] 2020-03-19 10:15
Closing this since I can't reproduce the issue.

**Closed by diogotcorreia** 2020-03-19 10:15 UTC
Labels: bug, can't reproduce
